const ROUTES = {
  HOME: 'INICIO',
  COURSES: {
    ROOT: 'CURSOS',
    PRE_UNIVERSITARIOS: {
      ROOT: 'PRE UNIVERSITARIOS',
      FACULTY_DETAILS: 'FACULTY_DETAILS',
    },
    UNIVERSITARIOS: {
      ROOT: 'UNIVERSITARIOS',
    },
    APOYO_ESCOLAR: {
      ROOT: 'APOYO_ESCOLAR',
    },
    DESARROLLO_DE_INTELIGENCIA: {
      ROOT: 'DESARROLLO_DE_INTELIGENCIA',
    },
  },
  GALLERY: 'GALERIA',
  ABOUT_US: 'QUIENES SOMOS',
};

export default ROUTES;
