const ROUTES = {
  HOME: 'INICIO',
  COURSES: 'CURSOS',
  GALLERY: 'GALERIA',
  ABOUT_US: 'QUIENES SOMOS',
  PRE_UNIVERSITARIOS: 'PRE_UNIVERSITARIOS',
  UNIVERSITARIOS: 'UNIVERSITARIOS',
  APOYO_ESCOLAR: 'APOYO_ESCOLAR',
  DESARROLLO_DE_INTELIGENCIA: 'DESARROLLO_DE_INTELIGENCIA',
  CAREER_LIST: 'CAREER_LIST'
};

export default ROUTES;
