const ROUTES = {
  HOME: 'HOME',
  COURSES: 'COURSES',
  PRE_UNIVERSITY_COURSES: 'PRE_UNIVERSITY_COURSES',
  FACULTY_DETAILS: 'FACULTY_DETAILS',
  PRE_UNIVERSITY_SUBJECT_DETAILS: 'PRE_UNIVERSITY_SUBJECT_DETAILS',
  ENROLLMENT_OPTIONS: 'ENROLLMENT_OPTIONS',
  SUBJECT_COURSES: 'SUBJECT_COURSES',
  SUBJECT_COURSE_DETAILS: 'SUBJECT_COURSE_DETAILS',
  ACADEMIC_LEVELING: 'ACADEMIC_LEVELING',
  ACADEMIC_LEVELING_DETAILS: 'ACADEMIC_LEVELING_DETAILS',
  CHESS: 'CHESS',
  GALLERY: 'GALLERY',
  ABOUT_US: 'ABOUT_US',
};

export default ROUTES;
